version: '3.8'

networks:
  app-net:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3003:3000'
    networks:
      - app-net
    depends_on:
      bd:
        condition: service_healthy

  bd:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - '5430:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5