// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: proto/receiver.proto

package grpc_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Receiver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *Receiver) Reset() {
	*x = Receiver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_receiver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Receiver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receiver) ProtoMessage() {}

func (x *Receiver) ProtoReflect() protoreflect.Message {
	mi := &file_proto_receiver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receiver.ProtoReflect.Descriptor instead.
func (*Receiver) Descriptor() ([]byte, []int) {
	return file_proto_receiver_proto_rawDescGZIP(), []int{0}
}

func (x *Receiver) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Receiver) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateReceiverRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Receiver *Receiver `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
}

func (x *CreateReceiverRequest) Reset() {
	*x = CreateReceiverRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_receiver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReceiverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReceiverRequest) ProtoMessage() {}

func (x *CreateReceiverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_receiver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReceiverRequest.ProtoReflect.Descriptor instead.
func (*CreateReceiverRequest) Descriptor() ([]byte, []int) {
	return file_proto_receiver_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReceiverRequest) GetReceiver() *Receiver {
	if x != nil {
		return x.Receiver
	}
	return nil
}

type CreateReceiverResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rid string `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
}

func (x *CreateReceiverResponse) Reset() {
	*x = CreateReceiverResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_receiver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReceiverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReceiverResponse) ProtoMessage() {}

func (x *CreateReceiverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_receiver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReceiverResponse.ProtoReflect.Descriptor instead.
func (*CreateReceiverResponse) Descriptor() ([]byte, []int) {
	return file_proto_receiver_proto_rawDescGZIP(), []int{2}
}

func (x *CreateReceiverResponse) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

type RetrieveReceiverRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rid string `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
}

func (x *RetrieveReceiverRequest) Reset() {
	*x = RetrieveReceiverRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_receiver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveReceiverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveReceiverRequest) ProtoMessage() {}

func (x *RetrieveReceiverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_receiver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveReceiverRequest.ProtoReflect.Descriptor instead.
func (*RetrieveReceiverRequest) Descriptor() ([]byte, []int) {
	return file_proto_receiver_proto_rawDescGZIP(), []int{3}
}

func (x *RetrieveReceiverRequest) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

type RetrieveReceiverResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Receiver *Receiver `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
}

func (x *RetrieveReceiverResponse) Reset() {
	*x = RetrieveReceiverResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_receiver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveReceiverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveReceiverResponse) ProtoMessage() {}

func (x *RetrieveReceiverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_receiver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveReceiverResponse.ProtoReflect.Descriptor instead.
func (*RetrieveReceiverResponse) Descriptor() ([]byte, []int) {
	return file_proto_receiver_proto_rawDescGZIP(), []int{4}
}

func (x *RetrieveReceiverResponse) GetReceiver() *Receiver {
	if x != nil {
		return x.Receiver
	}
	return nil
}

type UpdateReceiverRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Receiver *Receiver `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
}

func (x *UpdateReceiverRequest) Reset() {
	*x = UpdateReceiverRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_receiver_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReceiverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReceiverRequest) ProtoMessage() {}

func (x *UpdateReceiverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_receiver_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReceiverRequest.ProtoReflect.Descriptor instead.
func (*UpdateReceiverRequest) Descriptor() ([]byte, []int) {
	return file_proto_receiver_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateReceiverRequest) GetReceiver() *Receiver {
	if x != nil {
		return x.Receiver
	}
	return nil
}

type UpdateReceiverResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateReceiverResponse) Reset() {
	*x = UpdateReceiverResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_receiver_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReceiverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReceiverResponse) ProtoMessage() {}

func (x *UpdateReceiverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_receiver_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReceiverResponse.ProtoReflect.Descriptor instead.
func (*UpdateReceiverResponse) Descriptor() ([]byte, []int) {
	return file_proto_receiver_proto_rawDescGZIP(), []int{6}
}

type DeleteReceiverRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rid string `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
}

func (x *DeleteReceiverRequest) Reset() {
	*x = DeleteReceiverRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_receiver_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReceiverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReceiverRequest) ProtoMessage() {}

func (x *DeleteReceiverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_receiver_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReceiverRequest.ProtoReflect.Descriptor instead.
func (*DeleteReceiverRequest) Descriptor() ([]byte, []int) {
	return file_proto_receiver_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteReceiverRequest) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

type DeleteReceiverResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteReceiverResponse) Reset() {
	*x = DeleteReceiverResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_receiver_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReceiverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReceiverResponse) ProtoMessage() {}

func (x *DeleteReceiverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_receiver_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReceiverResponse.ProtoReflect.Descriptor instead.
func (*DeleteReceiverResponse) Descriptor() ([]byte, []int) {
	return file_proto_receiver_proto_rawDescGZIP(), []int{8}
}

var File_proto_receiver_proto protoreflect.FileDescriptor

var file_proto_receiver_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x22, 0x3e, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a,
	0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x22, 0x2a, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x69, 0x64,
	0x22, 0x2b, 0x0a, 0x17, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x69, 0x64, 0x22, 0x41, 0x0a,
	0x18, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x22, 0x3e, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x08, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x22, 0x18, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x29, 0x0a, 0x15, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x72, 0x69, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0xa3, 0x02, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x10, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65,
	0x76, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x18, 0x2e, 0x52, 0x65, 0x74,
	0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x41, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x72, 0x12, 0x16, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_receiver_proto_rawDescOnce sync.Once
	file_proto_receiver_proto_rawDescData = file_proto_receiver_proto_rawDesc
)

func file_proto_receiver_proto_rawDescGZIP() []byte {
	file_proto_receiver_proto_rawDescOnce.Do(func() {
		file_proto_receiver_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_receiver_proto_rawDescData)
	})
	return file_proto_receiver_proto_rawDescData
}

var file_proto_receiver_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_receiver_proto_goTypes = []interface{}{
	(*Receiver)(nil),                 // 0: Receiver
	(*CreateReceiverRequest)(nil),    // 1: CreateReceiverRequest
	(*CreateReceiverResponse)(nil),   // 2: CreateReceiverResponse
	(*RetrieveReceiverRequest)(nil),  // 3: RetrieveReceiverRequest
	(*RetrieveReceiverResponse)(nil), // 4: RetrieveReceiverResponse
	(*UpdateReceiverRequest)(nil),    // 5: UpdateReceiverRequest
	(*UpdateReceiverResponse)(nil),   // 6: UpdateReceiverResponse
	(*DeleteReceiverRequest)(nil),    // 7: DeleteReceiverRequest
	(*DeleteReceiverResponse)(nil),   // 8: DeleteReceiverResponse
}
var file_proto_receiver_proto_depIdxs = []int32{
	0, // 0: CreateReceiverRequest.receiver:type_name -> Receiver
	0, // 1: RetrieveReceiverResponse.receiver:type_name -> Receiver
	0, // 2: UpdateReceiverRequest.receiver:type_name -> Receiver
	1, // 3: ReceiverService.CreateReceiver:input_type -> CreateReceiverRequest
	3, // 4: ReceiverService.RetrieveReceiver:input_type -> RetrieveReceiverRequest
	5, // 5: ReceiverService.UpdateReceiver:input_type -> UpdateReceiverRequest
	7, // 6: ReceiverService.DeleteReceiver:input_type -> DeleteReceiverRequest
	2, // 7: ReceiverService.CreateReceiver:output_type -> CreateReceiverResponse
	4, // 8: ReceiverService.RetrieveReceiver:output_type -> RetrieveReceiverResponse
	6, // 9: ReceiverService.UpdateReceiver:output_type -> UpdateReceiverResponse
	8, // 10: ReceiverService.DeleteReceiver:output_type -> DeleteReceiverResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_receiver_proto_init() }
func file_proto_receiver_proto_init() {
	if File_proto_receiver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_receiver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Receiver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_receiver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReceiverRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_receiver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReceiverResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_receiver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveReceiverRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_receiver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveReceiverResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_receiver_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReceiverRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_receiver_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReceiverResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_receiver_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteReceiverRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_receiver_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteReceiverResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_receiver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_receiver_proto_goTypes,
		DependencyIndexes: file_proto_receiver_proto_depIdxs,
		MessageInfos:      file_proto_receiver_proto_msgTypes,
	}.Build()
	File_proto_receiver_proto = out.File
	file_proto_receiver_proto_rawDesc = nil
	file_proto_receiver_proto_goTypes = nil
	file_proto_receiver_proto_depIdxs = nil
}
